kind: pipeline
type: docker
name: azure-mlops-production-pipeline

trigger:
  branch:
    - main
  event:
    - push

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock


clone:
  disable: true

steps:
  - name: step-1-git-clone
    image: alpine/git:2.45.2
    commands:
      - git clone --depth=50 --branch "$DRONE_BRANCH" "$DRONE_REMOTE_URL" .
      - git checkout "$DRONE_COMMIT"


  - name: step-2-ml-training-logic
    image: python:3.10-slim
    environment:
      AZURE_STORAGE_CONNECTION_STRING:
        from_secret: azure_drone_storage_connection_string
    commands:
      # 1. Environment Setup
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install "dvc[azure]" pytest evidently==0.4.32
      - export PYTHONPATH=$${PYTHONPATH}:$(pwd)
      
      # 2. DVC Handshake
      #- dvc remote modify azure url azure://dvcstore
      - dvc remote modify --local azure connection_string "$${AZURE_STORAGE_CONNECTION_STRING}"
      - dvc config core.remote azure

      # 3. Pull Data from Azure
      - dvc pull -r azure --force

      # 4. Data Science Dependencies
      - python -c "import nltk; nltk.download('punkt'); nltk.download('punkt_tab'); nltk.download('stopwords'); nltk.download('wordnet'); nltk.download('omw-1.4')"
      
      # 5. Execute Pipeline & Tests
      - python -m pytest tests/pre -q || true
      - dvc repro 
      - python -m pytest tests/post -q || true
      
      # 6. Version and Push
      - dvc push -r azure

# Step 3a: Pull the model from Azure using Python/DVC
  - name: pull-model
    image: python:3.12-alpine
    environment:
      AZURE_STORAGE_CONNECTION_STRING:
        from_secret: azure_drone_storage_connection_string
    commands:
      - apk add --no-cache bash curl jq git
      - pip3 install "dvc[azure]"
      - dvc remote modify azure url azure://dvcstore
      - dvc remote modify --local azure connection_string "$AZURE_STORAGE_CONNECTION_STRING"
      - dvc config core.remote azure
      - dvc pull -r azure --force
  

  - name: step-3-docker-image-packaging
    image: docker:29
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      ACR_USERNAME:
        from_secret: ACR_USERNAME
      ACR_PASSWORD:
        from_secret: ACR_PASSWORD
    commands:
      - "sh -lc 'test -n \"$ACR_USERNAME\" || (echo \"Missing secret: ACR_USERNAME\" && exit 1)'"
      - "sh -lc 'test -n \"$ACR_PASSWORD\" || (echo \"Missing secret: ACR_PASSWORD\" && exit 1)'"
      - "sh -lc 'echo \"$ACR_PASSWORD\" | docker login \"mlopsacr123.azurecr.io\" -u \"$ACR_USERNAME\" --password-stdin'"
      - "sh -lc 'IMAGE_NAME=\"mlopsacr123.azurecr.io/mlops-api:drone-${DRONE_BUILD_NUMBER}\"; echo \"Building $IMAGE_NAME\"; docker build -t \"$IMAGE_NAME\" .; docker push \"$IMAGE_NAME\"'"


  - name: step-4-azure-app-deployment
    image: mcr.microsoft.com/azure-cli:2.60.0
    environment:
      AZURE_CREDENTIALS:
        from_secret: azure_drone_credentials
      AZURE_CONTAINER_APP:
        from_secret: azure_drone_container_app
      AZURE_RESOURCE_GROUP:
        from_secret: azure_drone_resource_group
    commands:
      - "apk add --no-cache jq curl"
      - "sh -lc 'echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6 || true'"
      - "sh -lc 'echo 1 > /proc/sys/net/ipv6/conf/default/disable_ipv6 || true'"
      - "sh -lc 'curl -4 -I https://login.microsoftonline.com --max-time 10 | head -n 1'"

      - "sh -lc 'echo \"$AZURE_CREDENTIALS\" > /tmp/azure.json'"
      - "sh -lc 'export AZURE_CLIENT_ID=$(jq -r \".clientId // empty\" /tmp/azure.json); echo AZURE_CLIENT_ID_len=${#AZURE_CLIENT_ID}'"
      - "sh -lc 'export AZURE_CLIENT_SECRET=$(jq -r \".clientSecret // empty\" /tmp/azure.json); echo AZURE_CLIENT_SECRET_len=${#AZURE_CLIENT_SECRET}'"
      - "sh -lc 'export AZURE_TENANT_ID=$(jq -r \".tenantId // empty\" /tmp/azure.json); echo AZURE_TENANT_ID_len=${#AZURE_TENANT_ID}'"
      - "sh -lc 'export AZURE_SUBSCRIPTION_ID=$(jq -r \".subscriptionId // empty\" /tmp/azure.json); echo AZURE_SUBSCRIPTION_ID_len=${#AZURE_SUBSCRIPTION_ID}'"

      - "sh -lc 'AZURE_CLIENT_ID=$(jq -r \".clientId // empty\" /tmp/azure.json); test -n \"$AZURE_CLIENT_ID\" || (echo \"Missing clientId\" && exit 1)'"
      - "sh -lc 'AZURE_CLIENT_SECRET=$(jq -r \".clientSecret // empty\" /tmp/azure.json); test -n \"$AZURE_CLIENT_SECRET\" || (echo \"Missing clientSecret\" && exit 1)'"
      - "sh -lc 'AZURE_TENANT_ID=$(jq -r \".tenantId // empty\" /tmp/azure.json); test -n \"$AZURE_TENANT_ID\" || (echo \"Missing tenantId\" && exit 1)'"
      - "sh -lc 'AZURE_SUBSCRIPTION_ID=$(jq -r \".subscriptionId // empty\" /tmp/azure.json); test -n \"$AZURE_SUBSCRIPTION_ID\" || (echo \"Missing subscriptionId\" && exit 1)'"

      - "sh -lc 'AZURE_CLIENT_ID=$(jq -r \".clientId\" /tmp/azure.json); AZURE_CLIENT_SECRET=$(jq -r \".clientSecret\" /tmp/azure.json); AZURE_TENANT_ID=$(jq -r \".tenantId\" /tmp/azure.json); az login --service-principal -u \"$AZURE_CLIENT_ID\" -p \"$AZURE_CLIENT_SECRET\" --tenant \"$AZURE_TENANT_ID\"'"
      - "sh -lc 'AZURE_SUBSCRIPTION_ID=$(jq -r \".subscriptionId\" /tmp/azure.json); az account set --subscription \"$AZURE_SUBSCRIPTION_ID\"'"

      - "sh -lc 'IMAGE_NAME=mlopsacr123.azurecr.io/mlops-api:drone-${DRONE_BUILD_NUMBER}; echo Deploying=$IMAGE_NAME; az containerapp update --name \"$AZURE_CONTAINER_APP\" --resource-group \"$AZURE_RESOURCE_GROUP\" --image \"$IMAGE_NAME\"'"
