kind: pipeline
type: docker
name: azure-mlops-production-pipeline

trigger:
  branch:
    - main
  event:
    - push

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock


clone:
  disable: true

steps:
  - name: step-1-git-clone
    image: alpine/git:2.45.2
    commands:
      - git clone --depth=50 --branch "$DRONE_BRANCH" "$DRONE_REMOTE_URL" .
      - git checkout "$DRONE_COMMIT"

  - name: step-2-ml-training-logic
    image: python:3.10-slim
    environment:
      AZURE_STORAGE_CONNECTION_STRING:
        from_secret: azure_drone_storage_connection_string
    commands:
      # 1. Environment Setup
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install "dvc[azure]" pytest evidently==0.4.32
      - export PYTHONPATH=$${PYTHONPATH}:$(pwd)
      
      # 2. DVC Handshake
      - dvc remote modify azure url azure://dvcstore
      - dvc remote modify azure connection_string "$${AZURE_STORAGE_CONNECTION_STRING}"
      - dvc config core.remote azure

      # 3. Pull Data from Azure
      - dvc pull -r azure --force

      # 4. Data Science Dependencies
      - python -c "import nltk; nltk.download('punkt'); nltk.download('punkt_tab'); nltk.download('stopwords'); nltk.download('wordnet'); nltk.download('omw-1.4')"
      
      # 5. Execute Pipeline & Tests
      - python -m pytest tests/pre -q || true
      - dvc repro 
      - python -m pytest tests/post -q || true
      
      # 6. Version and Push
      - dvc push -r azure

# Step 3a: Pull the model from Azure using Python/DVC
  - name: pull-model
    image: python:3.12-alpine
    environment:
      AZURE_STORAGE_CONNECTION_STRING:
        from_secret: azure_drone_storage_connection_string
    commands:
      - apk add --no-cache bash curl jq git
      - pip3 install "dvc[azure]"
      - dvc remote modify azure url azure://dvcstore
      - dvc remote modify azure connection_string "$AZURE_STORAGE_CONNECTION_STRING"
      - dvc pull -r azure --force

  - name: step-3-docker-image-packaging
    image: docker:29
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      AZURE_REGISTRY_NAME:
        from_secret: azure_drone_registry_name
      ACR_USERNAME:
        from_secret: ACR_USERNAME
      ACR_PASSWORD:
        from_secret: ACR_PASSWORD
    commands:
      - "sh -lc 'REG=${AZURE_REGISTRY_NAME:-mlopsacr123}; echo \"$REG\" > /tmp/REG'"
      - "sh -lc 'REG=$(cat /tmp/REG); echo \"Using registry: ${REG}.azurecr.io\"'"
      - "sh -lc 'test -n \"$ACR_USERNAME\" || (echo \"ACR_USERNAME is empty. Fix secret: ACR_USERNAME\" && exit 1)'"
      - "sh -lc 'test -n \"$ACR_PASSWORD\" || (echo \"ACR_PASSWORD is empty. Fix secret: ACR_PASSWORD\" && exit 1)'"
      - "sh -lc 'REG=$(cat /tmp/REG); echo \"$ACR_PASSWORD\" | docker login \"${REG}.azurecr.io\" -u \"$ACR_USERNAME\" --password-stdin'"
      - "sh -lc 'REG=$(cat /tmp/REG); IMAGE_NAME=\"${REG}.azurecr.io/mlops-api:v${DRONE_BUILD_NUMBER}\"; echo \"Building $IMAGE_NAME\"'"
      - "sh -lc 'REG=$(cat /tmp/REG); IMAGE_NAME=\"${REG}.azurecr.io/mlops-api:v${DRONE_BUILD_NUMBER}\"; docker build -t \"$IMAGE_NAME\" .'"
      - "sh -lc 'REG=$(cat /tmp/REG); IMAGE_NAME=\"${REG}.azurecr.io/mlops-api:v${DRONE_BUILD_NUMBER}\"; docker push \"$IMAGE_NAME\"'"





  - name: step-4-azure-app-deployment
    image: mcr.microsoft.com/azure-cli:2.60.0
    environment:
      AZURE_CREDENTIALS:
        from_secret: azure_drone_credentials
      AZURE_REGISTRY_NAME:
        from_secret: azure_drone_registry_name
      AZURE_CONTAINER_APP:
        from_secret: azure_drone_container_app
      AZURE_RESOURCE_GROUP:
        from_secret: azure_drone_resource_group
    commands:
      - apt-get update && apt-get install -y jq
      - echo "$AZURE_CREDENTIALS" > /tmp/azure.json
      - export AZURE_CLIENT_ID=$(jq -r .clientId /tmp/azure.json)
      - export AZURE_CLIENT_SECRET=$(jq -r .clientSecret /tmp/azure.json)
      - export AZURE_TENANT_ID=$(jq -r .tenantId /tmp/azure.json)
      - export AZURE_SUBSCRIPTION_ID=$(jq -r .subscriptionId /tmp/azure.json)
      - az login --service-principal -u "$AZURE_CLIENT_ID" -p "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"
      - az account set --subscription "$AZURE_SUBSCRIPTION_ID"
      - export IMAGE_NAME=${AZURE_REGISTRY_NAME}.azurecr.io/mlops-api:v${DRONE_BUILD_NUMBER}
      - az containerapp update --name "$AZURE_CONTAINER_APP" --resource-group "$AZURE_RESOURCE_GROUP" --image "$IMAGE_NAME"