kind: pipeline
type: docker
name: full-azure-mlops

trigger:
  event:
    - push
  branch:
    - main

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

steps:
  #######################################################
  # 1) TRAIN (DVC + Tests + Train + Push)
  #######################################################
  - name: train-and-version
    image: python:3.10-slim
    environment:
      AZURE_STORAGE_CONNECTION_STRING:
        from_secret: azure_drone_storage_connection_string
      AZURE_CONTAINER:
        from_secret: azure_drone_container
    commands:
      - python -V
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install "dvc[azure]" pytest evidently==0.4.32

      # DVC remote config (expects remote name "azure")
      - dvc remote modify azure connection_string "$AZURE_STORAGE_CONNECTION_STRING"
      - dvc remote modify azure container_name "$AZURE_CONTAINER"

      # Pull cache if exists
      - dvc pull -r azure --force -v || echo "No cache yet."

      # NLTK downloads
      - python - <<'EOF'
        import nltk
        nltk.download('punkt')
        nltk.download('punkt_tab')
        nltk.download('stopwords')
        nltk.download('wordnet')
        nltk.download('omw-1.4')
        EOF

      # tests + training
      - pytest tests/pre -q
      - python src/data_prep.py
      - python src/train.py
      - dvc repro
      - pytest tests/post -q

      # push artifacts
      - dvc push -r azure -v

  ########################################################
  # 2) BUILD DOCKER IMAGE (PULL MODELS FROM DVC, PUSH TO ACR)
  ########################################################
  - name: build-api-image
    image: docker:24
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      DOCKER_API_VERSION: "1.43"   # matches your Docker Desktop 24.x daemon API
      AZURE_STORAGE_CONNECTION_STRING:
        from_secret: azure_drone_storage_connection_string
      AZURE_CONTAINER:
        from_secret: azure_drone_container
      AZURE_REGISTRY_NAME:
        from_secret: azure_drone_registry_name
      AZURE_CREDENTIALS:
        from_secret: azure_drone_credentials
    commands:
      - apk add --no-cache bash curl python3 py3-pip jq git
      - pip3 install "dvc[azure]"

      # Pull artifacts needed for image (models, etc.)
      - dvc remote modify azure connection_string "$AZURE_STORAGE_CONNECTION_STRING"
      - dvc remote modify azure container_name "$AZURE_CONTAINER"
      - dvc pull -r azure --force -v

      # Azure login from JSON
      - echo "$AZURE_CREDENTIALS" > /tmp/azure.json
      - export AZURE_CLIENT_ID="$(jq -r .clientId /tmp/azure.json)"
      - export AZURE_CLIENT_SECRET="$(jq -r .clientSecret /tmp/azure.json)"
      - export AZURE_TENANT_ID="$(jq -r .tenantId /tmp/azure.json)"
      - export AZURE_SUBSCRIPTION_ID="$(jq -r .subscriptionId /tmp/azure.json)"

      # Guardrail: fail fast if subscriptionId is missing
      - |
        if [ -z "$AZURE_SUBSCRIPTION_ID" ] || [ "$AZURE_SUBSCRIPTION_ID" = "null" ]; then
          echo "ERROR: subscriptionId in azure_drone_credentials is null/empty. Fix the JSON secret."
          exit 1
        fi

      # Install Azure CLI (Alpine)
      - apk add --no-cache azure-cli

      - az login --service-principal -u "$AZURE_CLIENT_ID" -p "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"
      - az account set --subscription "$AZURE_SUBSCRIPTION_ID"

      # ACR login
      - az acr login --name "$AZURE_REGISTRY_NAME"

      # Build + push image tagged with build number (similar to github.run_number)
      - export IMAGE_NAME="${AZURE_REGISTRY_NAME}.azurecr.io/mlops-api:v${DRONE_BUILD_NUMBER}"
      - echo "Building: $IMAGE_NAME"
      - docker version
      - docker build -t "$IMAGE_NAME" .
      - docker push "$IMAGE_NAME"

  ########################################################
  # 3) DEPLOY TO AZURE CONTAINER APPS
  ########################################################
  - name: deploy-to-aca
    image: mcr.microsoft.com/azure-cli:2.60.0
    environment:
      AZURE_CREDENTIALS:
        from_secret: azure_drone_credentials
      AZURE_REGISTRY_NAME:
        from_secret: azure_drone_registry_name
      AZURE_CONTAINER_APP:
        from_secret: azure_drone_container_app
      AZURE_RESOURCE_GROUP:
        from_secret: azure_drone_resource_group
    commands:
      - apk add --no-cache jq || true

      - echo "$AZURE_CREDENTIALS" > /tmp/azure.json
      - export AZURE_CLIENT_ID="$(jq -r .clientId /tmp/azure.json)"
      - export AZURE_CLIENT_SECRET="$(jq -r .clientSecret /tmp/azure.json)"
      - export AZURE_TENANT_ID="$(jq -r .tenantId /tmp/azure.json)"
      - export AZURE_SUBSCRIPTION_ID="$(jq -r .subscriptionId /tmp/azure.json)"

      - |
        if [ -z "$AZURE_SUBSCRIPTION_ID" ] || [ "$AZURE_SUBSCRIPTION_ID" = "null" ]; then
          echo "ERROR: subscriptionId in azure_drone_credentials is null/empty. Fix the JSON secret."
          exit 1
        fi

      - az login --service-principal -u "$AZURE_CLIENT_ID" -p "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"
      - az account set --subscription "$AZURE_SUBSCRIPTION_ID"

      - export IMAGE_NAME="${AZURE_REGISTRY_NAME}.azurecr.io/mlops-api:v${DRONE_BUILD_NUMBER}"
      - echo "Deploying: $IMAGE_NAME"
      - az containerapp update \
          --name "$AZURE_CONTAINER_APP" \
          --resource-group "$AZURE_RESOURCE_GROUP" \
          --image "$IMAGE_NAME"
