kind: pipeline
type: docker
name: full-azure-mlops-pipeline

trigger:
  branch:
    - main

steps:
  # 1. CLONE & SETUP
  - name: clone
    image: alpine/git:2.45.2
    commands:
      - git clone --depth=50 --branch ${DRONE_BRANCH} ${DRONE_REMOTE_URL} .
      - git checkout ${DRONE_COMMIT}

  # 2. TRAINING & VERSIONING
  - name: train-and-version
    image: python:3.10-slim
    environment:
      AZURE_STORAGE_CONNECTION_STRING:
        from_secret: azure_drone_storage_connection_string
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install "dvc[azure]" pytest evidently==0.4.32
      - export PYTHONPATH=$${PYTHONPATH}:$(pwd)
      # Configure DVC with the exact secret
      - dvc remote modify azure connection_string "$${AZURE_STORAGE_CONNECTION_STRING}"
      - dvc pull -r azure --force || echo "No cache yet"
      # NLP Setup
      - python -c "import nltk; nltk.download('punkt'); nltk.download('punkt_tab'); nltk.download('stopwords'); nltk.download('wordnet'); nltk.download('omw-1.4')"
      # Run Pipeline
      - pytest tests/pre -q
      - dvc repro
      - pytest tests/post -q
      - dvc push -r azure

  # 3. BUILD DOCKER IMAGE
  - name: build-api-image
    image: plugins/docker
    settings:
      # Using the registry name secret for the login/repo path
      registry: 
        from_secret: azure_drone_registry_name
      repo: 
        from_secret: azure_drone_registry_name
      target: mlops-api
      tags:
        - v${DRONE_BUILD_NUMBER}
        - latest
      username:
        from_secret: ACR_USERNAME
      password:
        from_secret: ACR_PASSWORD
      # Ensure context is preserved for model files
      dockerfile: Dockerfile

  # 4. DEPLOY TO AZURE CONTAINER APPS
  - name: deploy-to-aca
    image: mcr.microsoft.com/azure-cli:2.60.0
    environment:
      AZURE_CREDENTIALS:
        from_secret: azure_drone_credentials
      AZURE_CONTAINER_APP:
        from_secret: azure_drone_container_app
      AZURE_RESOURCE_GROUP:
        from_secret: azure_drone_resource_group
      AZURE_REGISTRY_NAME:
        from_secret: azure_drone_registry_name
    commands:
      # Parse the JSON credentials for login
      - apt-get update && apt-get install -y jq
      - echo "$${AZURE_CREDENTIALS}" > azure_creds.json
      - export CLIENT_ID=$(jq -r .clientId azure_creds.json)
      - export CLIENT_SECRET=$(jq -r .clientSecret azure_creds.json)
      - export TENANT_ID=$(jq -r .tenantId azure_creds.json)
      - az login --service-principal -u "$${CLIENT_ID}" -p "$${CLIENT_SECRET}" --tenant "$${TENANT_ID}"
      # Perform the deployment update
      - |
        az containerapp update \
          --name $${AZURE_CONTAINER_APP} \
          --resource-group $${AZURE_RESOURCE_GROUP} \
          --image $${AZURE_REGISTRY_NAME}.azurecr.io/mlops-api:v$${DRONE_BUILD_NUMBER}